# Generated by Django 2.1.7 on 2019-02-27 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='local',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
