# Generated by Django 2.1.7 on 2019-03-25 18:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_empresas_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674)),
                ('nm_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('nm_regiao', models.CharField(blank=True, max_length=20, null=True)),
                ('cd_geocuf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SociodemografiaRmc',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('cd_geocodi', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('cd_geocodb', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cd_geocods', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_subdist', models.CharField(blank=True, max_length=60, null=True)),
                ('cd_geocodd', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_distrit', models.CharField(blank=True, max_length=60, null=True)),
                ('cd_geocodm', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_municip', models.CharField(blank=True, max_length=60, null=True)),
                ('nm_micro', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_meso', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_setor', models.FloatField(blank=True, null=True)),
                ('situacao_s', models.BigIntegerField(blank=True, null=True)),
                ('f25a60anos', models.IntegerField(blank=True, null=True)),
                ('mulheres_2', models.IntegerField(blank=True, null=True)),
                ('homens_25a', models.IntegerField(blank=True, null=True)),
                ('domicilio_field', models.IntegerField(blank=True, db_column='domicilio_', null=True)),
                ('pessoa_a', models.IntegerField(blank=True, null=True)),
                ('pessoa_b', models.IntegerField(blank=True, null=True)),
                ('pessoa_ab', models.IntegerField(blank=True, null=True)),
                ('ipc_ab', models.FloatField(blank=True, null=True)),
                ('potencial_field', models.FloatField(blank=True, db_column='potencial_', null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('densid_dem', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sociodemografia_rmc',
                'managed': False,
            },
        ),
    ]
